my_site_root/urls.py
from django.contrib import admin
from django.urls import include, path
from p_library import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index, name='books'),
    path('book_increment/', views.book_increment),
    path('book_decrement/', views.book_decrement),
    path('publish/', views.show_publishings, name='publish'),
    path('author/', include('p_library.urls'), name='author'),
    path('add_book/', views.BookCreate.as_view(), name='add-book'),

    path('accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

p_library/urls.py
from django.contrib import admin
from django.urls import path
from .views import AuthorEdit, AuthorList, author_create_many, books_authors_create_many, profilePage
from allauth.account.views import login, logout
from allauth.socialaccount.models import SocialAccount

app_name = 'p_library'
urlpatterns = [
    path('', AuthorList.as_view(), name='author'),
    path('create', AuthorEdit.as_view(), name='author_create'),
    path('create_many', author_create_many, name='author_create_many'),
    path('create_manyes', books_authors_create_many,
         name='book_author_create_many'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/',  profilePage, name='profile'),

]

p_library/models.py
from django.db import models


class Publishing(models.Model):
    name = models.CharField(max_length=20, default='')
    country = models.CharField(max_length=2)

    def __str__(self):
        return self.name


class Author(models.Model):
    full_name = models.TextField()
    birth_year = models.SmallIntegerField()
    country = models.CharField(max_length=2)

    def __str__(self):
        return self.full_name


class Friend(models.Model):
    full_name = models.CharField(max_length=25, default='', null=True)

    def __str__(self):
        return self.full_name


class Book(models.Model):
    ISBN = models.CharField(db_column='ISBN', max_length=13)
    title = models.TextField()
    description = models.TextField()
    year_release = models.SmallIntegerField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    price = models.DecimalField(
        max_digits=10, decimal_places=5, blank=True, null=True)
    copy_count = models.SmallIntegerField(blank=True, null=True)
    publishing = models.ForeignKey(
        Publishing, on_delete=models.CASCADE, related_name='publish', null=True)
    debeter = models.ManyToManyField(
        'Friend', through='Exchange', through_fields=('book', 'friend'), blank=True)
    cover = models.ImageField(
        upload_to='covers/', blank=True)

    # Я решил сделать связь ManyToMany дабы учесть возможность выдачи одной
    # книги нескольким друзьям. В конце концов, FOreignKey мы уже обсосали со всех сторон
    # в прошлых ДЗ. Но если тебе нужен именно один-ко-многим, то раскомментируй debeter ниже.
    # debeter = models.ForeignKey(
    #     Friend, models.DO_NOTHING, null=True)

    def __str__(self):
        return self.title


class Exchange(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    friend = models.ForeignKey(
        Friend, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.book.title} у {self.friend.full_name}'

p_library/views.py
from django.http import HttpResponse
from django.template import loader
from p_library.models import Book, Author, Publishing
from django.shortcuts import render, redirect
from p_library.form import AuthorForm, BookForm, SocialAccountForm, UserForm
from django.views.generic import CreateView, ListView, UpdateView
from django.urls import reverse_lazy
from django.forms import formset_factory
from django.http.response import HttpResponseRedirect
from allauth.socialaccount.models import SocialAccount
from django.contrib.auth.models import User


import pdb


# Create your views here.


def profilePage(request):
    context = {}
    if request.method == "POST":
        print("POST", request)
    if request.user.is_authenticated:

        context['username'] = request.user.username
        print('REQEST USER', request.user)
        try:
            context['extra'] = SocialAccount.objects.get(
                provider='github', user=request.user).extra_data
        except:

            context['user'] = User.objects.get(username=request.user.username)
            print(context['user'].first_name)

    return render(request, 'profile.html', context)


def books_authors_create_many(request):
    AuthorFormSet = formset_factory(AuthorForm, extra=2)
    BookFormSet = formset_factory(BookForm, extra=2)
    if request.method == "POST":
        author_formset = AuthorFormSet(
            request.POST, request.FILES, prefix='authors')
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')
        if author_formset.is_valid() and book_formset.is_valid():
            for author in author_formset:
                author.save()
            for book in book_formset:
                book.save()
            return HttpResponseRedirect(reverse_lazy('p_library:authors_list'))
    else:
        author_formset = AuthorFormSet(prefix='authors')
        book_formset = BookFormSet(prefix='books')
        return render(request, 'manage_books_authors.html', {'author_formset': author_formset, 'book_formset': book_formset})


def author_create_many(request):
    #
    AuthorFormSet = formset_factory(AuthorForm, extra=2)
    if request.method == "POST":
        author_formset = AuthorFormSet(
            request.POST, request.FILES, prefix='authors')
        if author_formset.is_valid():
            for author_form in author_formset:
                author_form.save()
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))
    else:
        author_formset = AuthorFormSet(prefix='authors')
        # pdb.set_trace()
        return render(request, 'manage_authors.html', {'author_formset': author_formset})


class BookCreate(CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('books')
    template_name = 'manage_books.html'


class AuthorEdit(CreateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy('p_library:author_list')
    template_name = 'author_edit.html'


class AuthorList(ListView):
    model = Author
    template_name = 'authors_list.html'


def books_list(request):
    books = Book.objects.all()
    return HttpResponse(books)


def index(request):
    template = loader.get_template('index.html')
    print('INDEX', request.user.username)
    books = Book.objects.all()
    books_list = [i for i in books]
    biblio_data = {'title': 'My library',
                   'books': books_list}

    return HttpResponse(template.render(biblio_data, request))


def show_publishings(request):
    """Показывает издательства и их книги по пути /publish
    Я решил, что вывести просто список издательств будет скучно,
    потому вывел таблицу в которой перечислены издательства, 
    а книги сгруппированы по издательствам(см /publish)."""

    template = loader.get_template('publishings/publishings.html')
    books = Book.objects.all()
    pubs = Publishing.objects.all()
    books_list = [i for i in books]
    pubs_list = [i for i in pubs]
    b_data = {'books': books_list, 'pubs': pubs_list}
    return HttpResponse(template.render(b_data, request))


def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('books')
        else:
            book = Book.objects.filter(id=book_id).first()
            book.copy_count += 1
            book.save()
        return redirect('books')
    else:
        return redirect('books')


def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('books')
        else:
            book = Book.objects.filter(id=book_id).first()
            if book.copy_count < 1:
                return redirect('books')
            else:
                book.copy_count -= 1
        book.save()
        return redirect('books')
    else:
        return redirect('books')

p_library/templates/author_edit.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Форма редактирования авторов</title>


</head>
<body>
 <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить">
    </form>
</body>
</html>

p_library/templates/authors_list.html
{% extends 'base.html' %}
{% block content %}

<title>Список Авторов</title>


<div class='content'>
    <ul>
        {% for author in object_list %}
        <li>{{ author.full_name }}</li>
        {% endfor %}
    </ul>

</div>
{% endblock %}

p_library/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body>
    <nav>
        <ul class='nav__menu'>
            <a href="{% url 'books' %}">Книги</a>
            <a href="{% url 'p_library:author' %}">Авторы</a>
            <a href="{% url 'publish' %}">Издательства</a>


            {% if user.username  %}
            <a href="{% url 'add-book' %}">Добавить книгу</a>

            {% else %}
            <div class="login-grp">Для добавления книги надо <a href="{% url 'p_library:login' %}">Войти</a></div>

            {% endif %}

        </ul>
    </nav>
    <div class="welcome">
        Hi {{user}}.

        {% if  user.username %}
        <a href="{% url 'p_library:profile' %}">Профиль</a>
        <a href="{% url 'p_library:logout' %}">Выйти</a>


        {% endif %}
    </div>
    <div>


        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

p_library/templates/index.html
{% extends 'base.html' %}

{% block content %}



<title>Список книг</title>
<div class="welcome">
    <div>Welcome to {{title}}.</div>
    <div>Here are {{ books|length }} books from my collection</div>
</div>

<div class="content">
    {% for book in books %}
    <div class="row">

        <div>{{ forloop.counter }}
            {% if book.cover %}
            <img src='media/{{book.cover}}' alt="" height="40vh">
            {% endif %}
        </div>

        <div> {{ book.title }}</div>
        <div>{{ book.ISBN }}</div>
        <div>{{ book.description }}</div>
        <div>{{ book.year_release }}</div>
        <div>{{ book.author.full_name }}</div>
        <div>{{ book.author.country }}</div>
        <div>{{ book.copy_count }}</div>
        <div>
            <form action="/book_increment/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ book.id }}" />
                <input type="submit" value="Увеличить количество">
            </form>
            <form action="/book_decrement/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ book.id }}" />
                <input type="submit" value="Уменьшить количество">
            </form>
        </div>
    </div>
    {% endfor %}


</div>
{% endblock %}

p_library/templates/manage_authors.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FormSets</title>

</head>
<body>

<form method="post">
    {% csrf_token %}
    {{ author_formset.management_form }}
    {% for form in author_formset %}
        {{form.as_ul}}
    <br>
    {% endfor %}
    <input type="submit" value="Сохранить">
</form>

</body>
</html>

p_library/templates/manage_books.html
{% extends 'base.html' %}
{% block content %}
<div>

    <form class='book-add__form' method="POST" enctype="multipart/form-data">
        {% csrf_token %}


        {{ form.as_p }}
        <br>
        <button class='save_book' type="submit">Сохранить книгу</button>
    </form>
</div>
{% endblock %}

p_library/templates/manage_books_authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>books & authors</title>

</head>
<body>

<form method="post">
    {% csrf_token %}
    {{author_formset.management_form}}
    {% for form in author_formset %}
        {{form.as_ul}}
    <br>
    {% endfor %}

    {{ book_formset.management_form }}
        {% for form in book_formset %}
            {{ form.as_ul }}
                <br>
        {% endfor %}
</form>

</body>
</html>

p_library/templates/profile.html
{% extends 'base.html' %}
{% block content %}

<!-- 
<form method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">

</form> -->

Привет, {{username}} <br>

{% if extra %}
{% for field, data in extra.items %}
{{field}}: <input type="text" id='{{field}}' value="{{data}}">
<br>
{% endfor %}
{% else %}

<p>Имя: <input type="text" id='first_name' value='{{user.first_name}}'></p>
<p>Фамилия: <input type="text" id='last_name' value='{{user.last_name}}'></p>
<p>email: <input type="text" id='email' value='{{user.email}}'></p>




{% endif %}

{% endblock %}

p_library/templates/publishings/publishings.html
{% extends 'base.html' %}



{% block content %}
<title>Publishings</title>
<div style="margin: 5px;">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th scope='col'>#</th>
                    <th scope='col'>Издательство</th>
                    <th scope='col'>Страна</th>
                    <th scope='col'>Книги</th>

                </tr>
            </thead>

            <tbody>
                {% for pub in pubs %}
                <tr scope='row'></tr>
                <td> {{ forloop.counter }} </td>
                <td> {{ pub.name }} </td>
                <td> {{ pub.country }} </td>
                <td> {% for book in books %}
                    {% if book.publishing.name == pub.name %}
                    {{ book.title }}<br>
                    {% endif %}
                    {% endfor %}
                </td>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock %}